# Generated by Django 4.1.3 on 2022-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Comment text')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('url', models.URLField()),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='home/page_info', verbose_name='Post photo')),
                ('text', models.TextField(max_length=225)),
            ],
            options={
                'verbose_name': 'Page information',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='home/post_photo', verbose_name='Post photo')),
                ('title', models.CharField(max_length=85, verbose_name='Title')),
                ('description', models.TextField(max_length=420, verbose_name='Description')),
                ('info_h', models.CharField(blank=True, max_length=55, null=True, verbose_name='Information header')),
                ('info', models.TextField(blank=True, max_length=220, null=True, verbose_name='Information')),
                ('status', models.CharField(choices=[('active', 'active'), ('block', 'block')], default='active', max_length=10, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('like_number', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Leave this tag empty.', null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Name')),
                ('text', models.TextField(default='No description for this tag.', max_length=220)),
                ('attr', models.CharField(default='bi-tag', max_length=30, verbose_name='Icon class name')),
                ('show', models.BooleanField(default=False, verbose_name='show in home page')),
                ('slug', models.SlugField(blank=True, help_text='Leave this tag empty.', null=True)),
            ],
            options={
                'ordering': ['-show'],
            },
        ),
    ]
